name: myenv
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-aarch64=2.44=h5e2c951_1
  - libexpat=2.7.1=hfae3067_0
  - libffi=3.4.6=he21f813_1
  - libgcc=15.1.0=he277a41_5
  - libgcc-ng=15.1.0=he9431aa_5
  - libgomp=15.1.0=he277a41_5
  - liblzma=5.8.1=h86ecc28_2
  - libnsl=2.0.1=h86ecc28_1
  - libsqlite=3.50.4=h022381a_0
  - libuuid=2.41.1=h3e4203c_0
  - libxcrypt=4.4.36=h31becfc_1
  - libzlib=1.3.1=h86ecc28_2
  - ncurses=6.5=ha32ae93_3
  - openssl=3.5.2=h8e36d6e_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=h256493d_0_cpython
  - readline=8.2=h8382b9d_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_h5688188_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beartype==0.22.2
      - braceexpand==0.1.7
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cosine-annealing-warmup==2.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - easydict==1.13
      - einops==0.8.1
      - ema-pytorch==0.7.7
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.13.1
      - flatbuffers==25.9.23
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - insightface==0.7.3
      - ipdb==0.13.13
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - loguru==0.7.3
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - ml-dtypes==0.5.3
      - mne==1.10.1
      - mpmath==1.3.0
      - multidict==6.6.4
      - munch==4.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - neurokit2==0.2.12
      - ninja==1.13.0
      - numba==0.63.1
      - numpy==2.2.6
      - onnx==1.19.1
      - onnx2torch==1.5.15
      - onnxruntime==1.23.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - prettytable==3.16.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pysam==0.23.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.5
      - pytorch-warmup==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.9.1
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.37.1
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - stack-data==0.6.3
      - stringzilla==4.2.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.19
      - tokenizers==0.22.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchdiffeq==0.2.5
      - torchmetrics==1.8.2
      - torchtools==0.3.5
      - torchvision==0.20.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - vitaldb==1.5.8
      - wandb==0.22.1
      - warmup-scheduler==0.3
      - wcwidth==0.2.13
      - webdataset==1.0.2
      - werkzeug==3.1.3
      - wfdb==4.3.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /u/ztshuai/.conda/envs/myenv
